---
output: github_document
editor_options:
  markdown:
    wrap: sentence
title: 'Cycling Uptake and Road Lighting: A Review'
bibliography: saturn.bib
---

# Abstract

<!-- Linear cycling infrastructure at ground level, such as cycle lanes, have received the bulk of research and policy attention in relation to investment in walking and cycling. -->

<!-- However, localised treatments such as appropriate lighting and cycle parking can have a major impact on cyclability. -->

There is evidence suggesting darkness puts people off from cycling, and increases the risk of being involved in a collision whilst cycling.
Appropriate road or path lighting can increase feelings of reassurance, make hazards more visible, and make the cyclist more visible to other road users.
However, there is to date little evidence on the lighting interventions that work best, in combination with other measures.
Lighting after dark has costs, both in terms of energy use and harmful ecological effects due to excess light pollution, raising the question: what is the optimal use of lighting to enable safe cycling uptake, at all times and in all seasons?

<!-- "Lighting to see and lighting to be seen by".-->

# Introduction

Research suggests that darkness influences negatively cycling uptake.
But to what extent?
Is this applicable to all groups of cyclists equally?
Is this due to fear of suffering a road collision or fear of another type of threat (crime)?

To the best of our knowledge, there is no academic paper that has reviewed the international literature available on this specific area of research. 
@fotios_lighting_2017 provide a review of suggested actions to enable cycling lighting to contribute to the safety of cyclists.
However, @fotios_lighting_2017 focuses on cycling safety and lighting in the UK.

This paper aims to review international research on the relationship between cycling uptake and road lighting.

<!-- Concepts to define? --> <!-- E.g. road lighting? -->

The review is organized as follows.
Chapter 2 describes the methodology used for the selection of papers.
Chapter 3 critically analyzes the reviewed articles and identifies gaps in the research.
Chapter 4 closes the work with the conclusions.

# Methodology

Good practice review methodology: Scheepers et al., 2014.
Selection of papers: SCOPUS search engine (any other? e.g. Google Scholar).
How have been systematically 'searched'?
Keywords used.
Boolean operators (AND, OR, NOT).
Information to provide: Databases Languages included Keywords Search strategy

We need to define scope of the review - we are looking at papers that: Investigate the effects of light and lighting in some way, including road lighting or ambient light, but excluding other types of lighting such as cycle-mounted lighting Relate to cycling rates or cycling propensity, i.e. not related to cyclist safety?
Other parameters for scope?
Results (or state of knowledge) What is already known in this area (and maybe what is not)?
Present the literature in a logical way, commenting on the differences and similarities between the material cited.
Potential outputs of this section: state of knowledge, gaps in literature, weakness of methodologies used, structure on how dependent and independent variables are related (conceptual model?).

Table with a summary of the most relevant literature.

# Discussion and research gaps

# Conclusions

Interpretation of the material.

The review presented above highlights the need for more empirical work in the area of cycling uptake (which means tackling the barriers to cycling including road safety and perceived personal safety) and lighting.
We plan to undertake some of this work over the coming months in the SATURN (Supporting Active Travel Using Road lighting at Night) project, which has been funded by the UK Research and Innovation body.
During the project we plan to measure change in cycling levels, primarily through cyclists counts, and cycling safety due to darkness as inferred from models of cycling levels and high resolution casualty over multi year timescales and in a number of different locations.
Comparing resulting estimates of change in cycling and safety levels will help assess the impact of lighting in those locations, but there is much else to do in this field beyond what is possible in a 24 month research project.
Further work is needed to better understand how lighting characteristics such as illuminance and the spatial distribution of lighting influence cycling rates and cyclist safety.
To ensure the policy relevance of future work into road lighting and cycling, it is important that the findings feed into larger models of cycling uptake to support cost effective investment in road and path lighting [@fotios_pilot_2017], as part of balanced packages of interventions, for the benefit of people who stand to benefit from better walking, cycling and wheeling provision worldwide.

# References
